# Generated by Django 3.1.2 on 2020-10-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='highlightedVicinity',
        ),
        migrations.RemoveField(
            model_name='property',
            name='vicinity',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(max_length=600),
        ),
    ]
