# Generated by Django 3.1.2 on 2020-10-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20201018_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_PhoneNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(max_length=50),
        ),
    ]
