# Generated by Django 3.1.2 on 2020-10-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20201025_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_PhoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
